In [29]:
import pandas as pd
train_data = pd.read_csv('./rainfall_train.csv')

test_data = pd.read_csv('./Test_rainfall_test_test.csv')

In [30]:
fc_year = 'rainfall_train.fc_year'
fc_month = 'rainfall_train.fc_month'
fc_day = 'rainfall_train.fc_day'
fc_hour = 'rainfall_train.fc_hour'
stn4contest = 'rainfall_train.stn4contest'
dh = 'rainfall_train.dh'
ef_year = 'rainfall_train.ef_year'
ef_month = 'rainfall_train.ef_month'
ef_day = 'rainfall_train.ef_day'
ef_hour = 'rainfall_train.ef_hour'
v01 = 'rainfall_train.v01'
v02 = 'rainfall_train.v02'
v03 = 'rainfall_train.v03'
v04 = 'rainfall_train.v04'
v05 = 'rainfall_train.v05'
v06 = 'rainfall_train.v06'
v07 = 'rainfall_train.v07'
v08 = 'rainfall_train.v08'
v09 = 'rainfall_train.v09'
vv = 'rainfall_train.vv'
class_interval = 'rainfall_train.class_interval'

In [31]:
column_mapping = {
    'rainfall_test.fc_year': 'rainfall_train.fc_year',
    'rainfall_test.fc_month': 'rainfall_train.fc_month',
    'rainfall_test.fc_day': 'rainfall_train.fc_day',
    'rainfall_test.fc_hour': 'rainfall_train.fc_hour',
    'rainfall_test.ef_year': 'rainfall_train.ef_year',
    'rainfall_test.ef_month': 'rainfall_train.ef_month',
    'rainfall_test.ef_day': 'rainfall_train.ef_day',
    'rainfall_test.ef_hour': 'rainfall_train.ef_hour',
    'rainfall_test.dh': 'rainfall_train.dh',
    'rainfall_test.stn4contest': 'rainfall_train.stn4contest',
    'rainfall_test.v01': 'rainfall_train.v01',
    'rainfall_test.v02': 'rainfall_train.v02',
    'rainfall_test.v03': 'rainfall_train.v03',
    'rainfall_test.v04': 'rainfall_train.v04',
    'rainfall_test.v05': 'rainfall_train.v05',
    'rainfall_test.v06': 'rainfall_train.v06',
    'rainfall_test.v07': 'rainfall_train.v07',
    'rainfall_test.v08': 'rainfall_train.v08',
    'rainfall_test.v09': 'rainfall_train.v09'
}

test_data = test_data.rename(columns=column_mapping)

In [32]:
print(train_data.dtypes)

Unnamed: 0                         int64
rainfall_train.fc_year            object
rainfall_train.fc_month            int64
rainfall_train.fc_day              int64
rainfall_train.fc_hour             int64
rainfall_train.stn4contest        object
rainfall_train.dh                  int64
rainfall_train.ef_year            object
rainfall_train.ef_month            int64
rainfall_train.ef_day              int64
rainfall_train.ef_hour             int64
rainfall_train.v01                 int64
rainfall_train.v02                 int64
rainfall_train.v03                 int64
rainfall_train.v04                 int64
rainfall_train.v05                 int64
rainfall_train.v06                 int64
rainfall_train.v07                 int64
rainfall_train.v08                 int64
rainfall_train.v09                 int64
rainfall_train.vv                float64
rainfall_train.class_interval      int64
dtype: object

In [33]:
print(test_data.dtypes)

rainfall_train.fc_year           object
rainfall_train.fc_month           int64
rainfall_train.fc_day             int64
rainfall_train.fc_hour            int64
rainfall_train.stn4contest       object
rainfall_train.dh                 int64
rainfall_train.ef_year           object
rainfall_train.ef_month           int64
rainfall_train.ef_day             int64
rainfall_train.ef_hour            int64
rainfall_train.v01                int64
rainfall_train.v02                int64
rainfall_train.v03                int64
rainfall_train.v04                int64
rainfall_train.v05                int64
rainfall_train.v06                int64
rainfall_train.v07                int64
rainfall_train.v08                int64
rainfall_train.v09                int64
rainfall_test.class_interval    float64
dtype: object

In [35]:
train_data.isnull().sum()

Unnamed: 0                       0
rainfall_train.fc_year           0
rainfall_train.fc_month          0
rainfall_train.fc_day            0
rainfall_train.fc_hour           0
rainfall_train.stn4contest       0
rainfall_train.dh                0
rainfall_train.ef_year           0
rainfall_train.ef_month          0
rainfall_train.ef_day            0
rainfall_train.ef_hour           0
rainfall_train.v01               0
rainfall_train.v02               0
rainfall_train.v03               0
rainfall_train.v04               0
rainfall_train.v05               0
rainfall_train.v06               0
rainfall_train.v07               0
rainfall_train.v08               0
rainfall_train.v09               0
rainfall_train.vv                0
rainfall_train.class_interval    0
dtype: int64

In [36]:
test_data.isnull().sum()

rainfall_train.fc_year               0
rainfall_train.fc_month              0
rainfall_train.fc_day                0
rainfall_train.fc_hour               0
rainfall_train.stn4contest           0
rainfall_train.dh                    0
rainfall_train.ef_year               0
rainfall_train.ef_month              0
rainfall_train.ef_day                0
rainfall_train.ef_hour               0
rainfall_train.v01                   0
rainfall_train.v02                   0
rainfall_train.v03                   0
rainfall_train.v04                   0
rainfall_train.v05                   0
rainfall_train.v06                   0
rainfall_train.v07                   0
rainfall_train.v08                   0
rainfall_train.v09                   0
rainfall_test.class_interval    121870
dtype: int64

In [37]:
# # 예: 특정 월 필터링
# train_data = train_data[(train_data['rainfall_train.fc_month'].isin([5, 6, 7, 8, 9])) & 
#                         (train_data['rainfall_train.ef_month'].isin([5, 6, 7, 8, 9]))]

# test_data = test_data[(test_data['rainfall_train.fc_month'].isin([5, 6, 7, 8, 9])) & 
#                       (test_data['rainfall_train.ef_month'].isin([5, 6, 7, 8, 9]))]

# 카테고리형 변환
train_data['rainfall_train.fc_year'] = train_data['rainfall_train.fc_year'].astype('category').cat.codes
train_data['rainfall_train.ef_year'] = train_data['rainfall_train.ef_year'].astype('category').cat.codes
train_data['rainfall_train.stn4contest'] = train_data['rainfall_train.stn4contest'].astype('category').cat.codes

# test_data['rainfall_train.fc_year'] = test_data['rainfall_train.fc_year'].astype('category').cat.codes
# test_data['rainfall_train.ef_year'] = test_data['rainfall_train.ef_year'].astype('category').cat.codes
# test_data['rainfall_train.stn4contest'] = test_data['rainfall_train.stn4contest'].astype('category').cat.codes

In [ ]:
# if 'class interval' in train_data.columns:
#     train_data['class interval'] = train_data['class interval'].astype(int)

# if 'class interval' in test_data.columns:
#     test_data['class interval'] = test_data['class interval'].astype(int)

In [38]:
train_data.head()

,Unnamed: 0,rainfall_train.fc_year,rainfall_train.fc_month,rainfall_train.fc_day,rainfall_train.fc_hour,rainfall_train.stn4contest,rainfall_train.dh,rainfall_train.ef_year,rainfall_train.ef_month,rainfall_train.ef_day,...,rainfall_train.v02,rainfall_train.v03,rainfall_train.v04,rainfall_train.v05,rainfall_train.v06,rainfall_train.v07,rainfall_train.v08,rainfall_train.v09,rainfall_train.vv,rainfall_train.class_interval
0,1,0,5,1,9,0,3,0,5,1,...,0,0,0,0,0,0,0,0,0.0,0
1,2,0,5,1,9,0,6,0,5,1,...,0,0,0,0,0,0,0,0,0.0,0
2,3,0,5,1,9,0,9,0,5,1,...,0,0,0,0,0,0,0,0,0.0,0
3,4,0,5,1,9,0,12,0,5,1,...,0,0,0,0,0,0,0,0,0.0,0
4,5,0,5,1,9,0,15,0,5,2,...,0,0,0,0,0,0,0,0,0.0,0

In [39]:
test_data.head()

,rainfall_train.fc_year,rainfall_train.fc_month,rainfall_train.fc_day,rainfall_train.fc_hour,rainfall_train.stn4contest,rainfall_train.dh,rainfall_train.ef_year,rainfall_train.ef_month,rainfall_train.ef_day,rainfall_train.ef_hour,rainfall_train.v01,rainfall_train.v02,rainfall_train.v03,rainfall_train.v04,rainfall_train.v05,rainfall_train.v06,rainfall_train.v07,rainfall_train.v08,rainfall_train.v09,rainfall_test.class_interval
0,D,5,1,9,STN031,3,D,5,1,12,68,46,13,1,0,0,0,0,0,NaN
1,D,5,1,9,STN031,6,D,5,1,15,83,66,26,5,0,0,0,0,0,NaN
2,D,5,1,9,STN031,9,D,5,1,18,17,6,0,0,0,0,0,0,0,NaN
3,D,5,1,9,STN031,12,D,5,1,21,0,0,0,0,0,0,0,0,0,NaN
4,D,5,1,9,STN031,15,D,5,2,0,0,0,0,0,0,0,0,0,0,NaN

In [40]:
features = [
    fc_year, fc_month, fc_day, fc_hour, stn4contest, dh,
      ef_year, ef_month, ef_day, ef_hour, 
       v01, v02, v03, v04, v05, v06, v07, v08, v09]

In [41]:
# 각 확률값을 실제 확률로 (0.0~1.0)
for col in [v01, v02, v03, v04, v05, v06, v07, v08, v09]:
    train_data[col] = train_data[col]/100

In [42]:
#구간 중간값
intervals = [0.05, 0.15, 0.35, 0.75, 1.5, 3.5, 8.5, 15.0, 25.0]

In [43]:
# 각 구간 중간값 * 해당 확률 값 합산-> 예상 강수량 계산
test_data [vv] = (
        intervals[0] * test_data['rainfall_train.v01'] +
        intervals[1] * test_data['rainfall_train.v02'] +
        intervals[2] * test_data['rainfall_train.v03'] +
        intervals[3] * test_data['rainfall_train.v04'] +
        intervals[4] * test_data['rainfall_train.v05'] +
        intervals[5] * test_data['rainfall_train.v06'] +
        intervals[6] * test_data['rainfall_train.v07'] +
        intervals[7] * test_data['rainfall_train.v08'] +
        intervals[8] * test_data['rainfall_train.v09']
    )

In [45]:
X = train_data[features]
y = train_data[vv]

In [46]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [47]:
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor

# 모델
rf = RandomForestRegressor(n_estimators=100, random_state=42)
etr = ExtraTreesRegressor(n_estimators=100, random_state=42)

models = {
    'rf' : RandomForestRegressor(n_estimators=100, random_state=42),
    'etr' : ExtraTreesRegressor(n_estimators=100, random_state=42)}

In [48]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

sample_size = 200000
X_train_sample = X_train.sample(n=sample_size, random_state=42)
y_train_sample = y_train.loc[X_train_sample.index]

# param_distributions = {
#     'n_estimators': randint(10, 200),
#     'max_features': randint(1, X_train_sample.shape[1]),
#     'max_depth': randint(1, 20),
#     'min_samples_split': randint(2, 20),
#     'min_samples_leaf': randint(1, 20)
#     }

In [ ]:
# from sklearn.metrics import mean_squared_error, r2_score

# models = {'etr':etr, 'rf':rf}
# for name, model in models.items():
#     model.fit(X_train, y_train)
#     train_score = model.score(X_train, y_train)
#     predictions = model.predict(X_test)
#     mse = mean_squared_error(y_test, predictions)
#     test_score = r2_score(y_test, predictions)
#     print(f'{name} Train Score: {train_score}')
#     print(f'{name} Test MSE: {mse}')
#     print(f'{name} Test Score: {test_score}')

In [ ]:
# from sklearn.model_selection import RandomizedSearchCV
# from scipy.stats import randint

# sample_size = 100000
# X_train_sample = X_train_split.sample(n=sample_size, random_state=42)
# y_train_sample = y_train_split.loc[X_train_sample.index]

# param_distributions = {
#     'n_estimators': randint(10, 200),
#     'max_features': randint(1, X_train_sample.shape[1]),
#     'max_depth': randint(1, 20),
#     'min_samples_split': randint(2, 20),
#     'min_samples_leaf': randint(1, 20)
# }

In [ ]:
# from sklearn.metrics import mean_squared_error, r2_score

# best_estimators = {}
# for name, model in models.items():
#     random_search = RandomizedSearchCV(model, param_distributions, n_iter=50, cv=3, 
#                                        scoring='neg_mean_squared_error', n_jobs=-1, verbose=1)
#     random_search.fit(X_train_sample, y_train_sample)
#     best_estimators[name] = random_search.best_estimator_
#     print(f"{name} 최적 파라미터: {random_search.best_params_}")
    
#     predictions = random_search.predict(X_test)
#     mse = mean_squared_error(y_test, predictions)
#     print(f"{name} 검증 MSE: {mse}")

#     mse = mean_squared_error(y_test, predictions)
#     test_score1 = r2_score(y_test, predictions)

#     print(f'{name} Train Score: {train_score}')
#     print(f'{name} Test MSE: {mse}')
#     print(f'{name} Test Score r2: {test_score1}')

In [ ]:
# best_estimators = {}
# for model_name, model in models.items():
#     grid_search = TQDMSearchCV(model, param_grid, cv=5, scoring='neg_mean_squared_error')
#     grid_search.fit(X_train_split, y_train_split)
#     best_estimators[model_name] = grid_search.best_estimator_
#     print(f"{model_name} best params: {grid_search.best_params_}")
#     y_pred = grid_search.predict(X_test)
#     mse = mean_squared_error(y_test, y_pred)
#     print(f"{model_name} validation MSE: {mse}")

In [49]:
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import RandomizedSearchCV
import numpy as np

models = {
    'etr': etr,
    'rf': rf
}

param_distributions = {
    'etr': {
        'n_estimators': np.arange(100, 300, 100),
        'max_features': ['sqrt', 'log2'],  # 'auto' 대신 'sqrt' 또는 'log2' 사용
        'max_depth': [None] + list(np.arange(10, 110, 10)),
        'min_samples_split': np.arange(2, 20, 2),
        'min_samples_leaf': np.arange(1, 20, 2)
    },
    'rf': {
        'n_estimators': np.arange(100, 300, 100),
        'max_features': ['sqrt', 'log2'],  # 'auto' 대신 'sqrt' 또는 'log2' 사용
        'max_depth': [None] + list(np.arange(10, 110, 10)),
        'min_samples_split': np.arange(2, 20, 2),
        'min_samples_leaf': np.arange(1, 20, 2)
    }
}

In [20]:
best_estimators = {}

for name, model in models.items():
    random_search = RandomizedSearchCV(model, param_distributions[name], n_iter=50, cv=3,
                                       scoring='neg_mean_squared_error', n_jobs=-1, verbose=1)
    random_search.fit(X_train_sample, y_train_sample)
    best_estimators[name] = random_search.best_estimator_
    print(f"{name} 최적 파라미터: {random_search.best_params_}")

    predictions = random_search.predict(X_test)
    mse = mean_squared_error(y_test, predictions)
    print(f"{name} 검증 mse : {mse}")

    test_score1 = r2_score(y_test, predictions)
    print(f"{name} test score r2: {test_score1}")

predictions_ensemble = np.zeros_like(y_test, dtype=float)

# 최적 모델-전체 데이터 다시 학습
for name, best_estimators in best_estimators.items():
    best_estimators.fit(X_train, y_train)
    # 최적 모델-전체 데이터 성능 평가
    train_score = best_estimators.score(X_train, y_train)
    predictions = best_estimators.predict(X_test)

    predictions_ensemble += predictions / len(best_estimators)

    mse = mean_squared_error(y_test, predictions)
    test_score = r2_score(y_test, predictions)

    print(f"{name} 최종 모델 train score : {train_score}")
    print(f"{name} 최종 모델 test mse : {mse}")
    print(f"{name} 최종 모델 test score r2 : {test_score}")


# 앙상블 성능 평가
mse_ensemble = mean_squared_error(y_test, predictions_ensemble)
test_score_ensemble = r2_score(y_test, predictions_ensemble)

print(f"앙상블 모델 Test MSE: {mse_ensemble}")
print(f"앙상블 모델 Test Score r2: {test_score_ensemble}")

Fitting 3 folds for each of 50 candidates, totalling 150 fits
etr 최적 파라미터: {'n_estimators': 100, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'log2', 'max_depth': 60}
etr 검증 mse : 4980.975264178476
etr test score r2: 0.13251533311049524
Fitting 3 folds for each of 50 candidates, totalling 150 fits
rf 최적 파라미터: {'n_estimators': 200, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'log2', 'max_depth': 100}
rf 검증 mse : 4664.366713455948
rf test score r2: 0.18765575212303587
etr 최종 모델 train score : 0.8515582948748112
etr 최종 모델 test mse : 4509.572182285529
etr 최종 모델 test score r2 : 0.21461470597980326
rf 최종 모델 train score : 0.9071807908383654
rf 최종 모델 test mse : 3940.048057295571
rf 최종 모델 test score r2 : 0.3138028006096881
앙상블 모델 Test MSE: 5731.424351332986
앙상블 모델 Test Score r2: 0.0018174191759370295

In [21]:
import pandas as pd

# 예측 결과를 pandas 시리즈로 변환
test_predictions_series = pd.Series(predictions)

In [22]:
print(predictions)

[ 0.0000e+00  0.0000e+00  4.0000e-02 ... -8.4915e+01  0.0000e+00
 -2.4275e+00]

In [23]:
print(f"{best_estimators} 최종 모델 train score : {train_score}")
print(f"{best_estimators} 최종 모델 test score : {test_score}")

RandomForestRegressor(max_depth=100, max_features='log2', n_estimators=200,
                      random_state=42) 최종 모델 train score : 0.9071807908383654
RandomForestRegressor(max_depth=100, max_features='log2', n_estimators=200,
                      random_state=42) 최종 모델 test score : 0.3138028006096881

In [24]:
# 예측 값 -> class_interval
def vv_to_class_interval(vv):
    if vv <= 0.1:
        return 0
    elif 0.1< vv <= 0.2:
        return 1
    elif 0.2 < vv <= 0.5:
        return 2
    elif 0.5 < vv <= 1.0:
        return 3
    elif 1.0 < vv <= 2.0:
        return 4
    elif 2.0 < vv <= 5.0:
        return 5
    elif 5.0 < vv <= 10.0:
        return 6
    elif 10.0 < vv <= 20.0:
        return 7
    elif 20.0 < vv <= 30.0:
        return 8
    else :
        return 9

In [25]:
test_data['rainfall_test.vv']=test_predictions_series
print(test_data['rainfall_test.vv'])

0         0.0000
1         0.0000
2         0.0400
3         0.0000
4         2.5095
           ...
121995   -7.7855
121996    0.0045
121997    0.0000
121998    0.0000
121999    0.0000
Name: rainfall_test.vv, Length: 122000, dtype: float64

In [26]:
# 예측 결과에 함수 적용
test_data['rainfall_test.class_interval'] = test_predictions_series.apply(vv_to_class_interval)

# 결과 확인
print(test_data['rainfall_test.class_interval'])

0         0
1         0
2         0
3         0
4         5
         ..
121995    0
121996    0
121997    0
121998    0
121999    0
Name: rainfall_test.class_interval, Length: 122000, dtype: int64

In [27]:
# 원래 컬럼명을 키로, 변경된 컬럼명을 값으로 하는 역 매핑 생성
reverse_column_mapping = {v: k for k, v in column_mapping.items()}

# 컬럼명을 원래대로 되돌리기
test_data = test_data.rename(columns=reverse_column_mapping)

In [28]:
test_data.to_csv('./240484.csv', index=False)